# Generated by Django 4.1.7 on 2023-03-18 15:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0005_employe_titre'),
    ]

    operations = [
        migrations.AddField(
            model_name='employe',
            name='fonction',
            field=models.CharField(default='employe', max_length=250),
            preserve_default=False,
        ),
    ]
